#!/usr/bin/env bash

ROOT_DIR="${ROOT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
BACKEND_DIR="${BACKEND_DIR:-$ROOT_DIR/backend}"
REPORT_DIR="${REPORT_DIR:-$ROOT_DIR/docs/reports}"
STATE_DIR="${STATE_DIR:-$ROOT_DIR/.rehearsal}"

POSTGRES_CONTAINER_NAME="${POSTGRES_CONTAINER_NAME:-xiyu-bid-rehearsal-postgres}"
REDIS_CONTAINER_NAME="${REDIS_CONTAINER_NAME:-xiyu-bid-rehearsal-redis}"
POSTGRES_PORT="${POSTGRES_PORT:-55432}"
REDIS_PORT="${REDIS_PORT:-56379}"
BACKEND_PORT="${BACKEND_PORT:-18080}"
FRONTEND_PORT="${FRONTEND_PORT:-14173}"

DB_HOST="${DB_HOST:-127.0.0.1}"
DB_PORT="${DB_PORT:-$POSTGRES_PORT}"
DB_NAME="${DB_NAME:-xiyu_bid}"
DB_USER="${DB_USER:-xiyu_user}"
DB_USERNAME="${DB_USERNAME:-$DB_USER}"
DB_PASSWORD="${DB_PASSWORD:-XiyuDB!2026}"
JWT_SECRET="${JWT_SECRET:-xiyu-go-live-jwt-secret-2026-with-32-chars}"
SPRING_PROFILES_ACTIVE="${SPRING_PROFILES_ACTIVE:-prod}"
REDIS_HOST="${REDIS_HOST:-127.0.0.1}"
CORS_ALLOWED_ORIGINS="${CORS_ALLOWED_ORIGINS:-http://127.0.0.1:${FRONTEND_PORT},http://localhost:${FRONTEND_PORT}}"
PLATFORM_ACCOUNT_ENCRYPTION_KEY="${PLATFORM_ACCOUNT_ENCRYPTION_KEY:-xiyu-platform-key-2026}"

UAT_API_BASE_URL="${UAT_API_BASE_URL:-http://127.0.0.1:${BACKEND_PORT}}"
UAT_WEB_BASE_URL="${UAT_WEB_BASE_URL:-http://127.0.0.1:${FRONTEND_PORT}}"

export ROOT_DIR BACKEND_DIR REPORT_DIR STATE_DIR
export POSTGRES_CONTAINER_NAME REDIS_CONTAINER_NAME POSTGRES_PORT REDIS_PORT BACKEND_PORT FRONTEND_PORT
export DB_HOST DB_PORT DB_NAME DB_USER DB_USERNAME DB_PASSWORD JWT_SECRET SPRING_PROFILES_ACTIVE REDIS_HOST
export CORS_ALLOWED_ORIGINS
export PLATFORM_ACCOUNT_ENCRYPTION_KEY UAT_API_BASE_URL UAT_WEB_BASE_URL

mkdir -p "$REPORT_DIR" "$STATE_DIR"
