    create table accounts (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        industry varchar(100),
        region varchar(100),
        name varchar(200) not null unique,
        contact_info varchar(500),
        credit_level varchar(255) not null check (credit_level in ('A','B','C','D')),
        type varchar(255) not null check (type in ('CLIENT','SUPPLIER','PARTNER','GOVERNMENT','OTHER')),
        primary key (id)
    );

    create table alert_history (
        resolved boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        resolved_at timestamp(6),
        rule_id bigint not null,
        related_id varchar(100),
        level varchar(255) not null check (level in ('LOW','MEDIUM','HIGH','CRITICAL')),
        message TEXT not null,
        primary key (id)
    );

    create table alert_rules (
        enabled boolean not null,
        threshold numeric(19,2) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        created_by varchar(100) not null,
        name varchar(200) not null,
        condition varchar(255) not null check (condition in ('GREATER_THAN','LESS_THAN','EQUALS','CONTAINS')),
        type varchar(255) not null check (type in ('DEADLINE','BUDGET','RISK','DOCUMENT')),
        primary key (id)
    );

    create table assembly_templates (
        created_at timestamp(6) not null,
        created_by bigint,
        id bigint generated by default as identity,
        name varchar(200) not null,
        category varchar(255),
        description TEXT,
        template_content TEXT not null,
        variables TEXT,
        primary key (id)
    );

    create table audit_logs (
        success boolean not null,
        id bigint generated by default as identity,
        timestamp timestamp(6) not null,
        action varchar(50) not null,
        ip_address varchar(50),
        entity_id varchar(100),
        entity_type varchar(100),
        username varchar(100),
        description varchar(500),
        user_agent varchar(500),
        error_message TEXT,
        new_value TEXT,
        old_value TEXT,
        user_id varchar(255) not null,
        primary key (id)
    );

    create table bar_assets (
        acquire_date date not null,
        asset_value numeric(19,2) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        name varchar(200) not null,
        remark varchar(500),
        status varchar(255) not null check (status in ('AVAILABLE','IN_USE','MAINTENANCE','RETIRED','DISPOSED')),
        type varchar(255) not null check (type in ('EQUIPMENT','FACILITY','VEHICLE','INVENTORY','LICENSE','OTHER')),
        primary key (id)
    );

    create table bar_certificate_borrow_records (
        expected_return_date date,
        borrowed_at timestamp(6) not null,
        certificate_id bigint not null,
        id bigint generated by default as identity,
        project_id bigint,
        returned_at timestamp(6),
        status varchar(30) not null check (status in ('BORROWED','RETURNED')),
        borrower varchar(100) not null,
        purpose varchar(200),
        remark varchar(500),
        primary key (id)
    );

    create table bar_certificates (
        expected_return_date date,
        expiry_date date,
        bar_asset_id bigint not null,
        created_at timestamp(6) not null,
        current_project_id bigint,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        status varchar(30) not null check (status in ('AVAILABLE','BORROWED','EXPIRED','DISABLED')),
        current_borrower varchar(100),
        holder varchar(100),
        provider varchar(100),
        type varchar(100) not null,
        borrow_purpose varchar(200),
        location varchar(200),
        serial_no varchar(200) not null,
        remark varchar(500),
        primary key (id)
    );

    create table calendar_events (
        event_date date not null,
        is_urgent boolean,
        created_at timestamp(6),
        id bigint generated by default as identity,
        project_id bigint,
        updated_at timestamp(6),
        event_type varchar(20) not null check (event_type in ('DEADLINE','MEETING','MILESTONE','REMINDER','SUBMISSION','REVIEW')),
        title varchar(500) not null,
        description TEXT,
        primary key (id)
    );

    create table cases (
        amount numeric(38,2) not null,
        project_date date,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        description TEXT,
        industry varchar(255) not null check (industry in ('REAL_ESTATE','INFRASTRUCTURE','MANUFACTURING','ENERGY','TRANSPORTATION','ENVIRONMENTAL','OTHER')),
        outcome varchar(255) not null check (outcome in ('WON','LOST','IN_PROGRESS')),
        title varchar(255) not null,
        primary key (id)
    );

    create table collaboration_threads (
        created_at timestamp(6) not null,
        created_by bigint,
        id bigint generated by default as identity,
        project_id bigint not null,
        updated_at timestamp(6),
        status varchar(30) not null check (status in ('OPEN','IN_PROGRESS','RESOLVED','CLOSED')),
        title varchar(500) not null,
        primary key (id)
    );

    create table comments (
        is_deleted boolean,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        parent_id bigint,
        thread_id bigint not null,
        updated_at timestamp(6),
        user_id bigint not null,
        content TEXT not null,
        mentions varchar(255),
        primary key (id)
    );

    create table competition_analyses (
        win_probability numeric(5,2),
        analysis_date timestamp(6),
        competitor_id bigint,
        id bigint generated by default as identity,
        project_id bigint not null,
        competitive_advantage TEXT,
        recommended_strategy TEXT,
        risk_factors TEXT,
        primary key (id)
    );

    create table competitors (
        market_share numeric(5,2),
        typical_bid_range_max numeric(19,2),
        typical_bid_range_min numeric(19,2),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        industry varchar(100),
        name varchar(200) not null,
        strengths TEXT,
        weaknesses TEXT,
        primary key (id)
    );

    create table compliance_check_results (
        risk_score integer not null,
        checked_at timestamp(6) not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        project_id bigint,
        tender_id bigint,
        updated_at timestamp(6),
        overall_status varchar(50) not null check (overall_status in ('COMPLIANT','NON_COMPLIANT','PARTIAL_COMPLIANT','WARNING')),
        checked_by varchar(100),
        check_details TEXT,
        primary key (id)
    );

    create table compliance_rules (
        enabled boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        rule_type varchar(50) not null check (rule_type in ('QUALIFICATION','DOCUMENT','FINANCIAL','EXPERIENCE','DEADLINE')),
        name varchar(200) not null,
        description varchar(1000),
        rule_definition TEXT,
        primary key (id)
    );

    create table dimension_scores (
        score integer,
        weight numeric(38,2),
        analysis_id bigint not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        dimension_name varchar(100) not null,
        comments TEXT,
        primary key (id)
    );

    create table document_assemblies (
        assembled_at timestamp(6) not null,
        assembled_by bigint,
        id bigint generated by default as identity,
        project_id bigint not null,
        template_id bigint,
        assembled_content TEXT,
        variables TEXT,
        primary key (id)
    );

    create table document_sections (
        order_index integer,
        created_at timestamp(6),
        id bigint generated by default as identity,
        parent_id bigint,
        structure_id bigint not null,
        updated_at timestamp(6),
        content TEXT,
        metadata varchar(255),
        section_type varchar(255) check (section_type in ('CHAPTER','SECTION','SUBSECTION','TABLE','IMAGE','ATTACHMENT')),
        title varchar(255) not null,
        primary key (id)
    );

    create table document_assignments (
        due_date date,
        assigned_by bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        project_id bigint not null,
        section_id bigint not null unique,
        updated_at timestamp(6) not null,
        owner varchar(100) not null,
        primary key (id)
    );

    create table document_locks (
        locked boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        locked_at timestamp(6),
        locked_by bigint,
        project_id bigint not null,
        section_id bigint not null unique,
        updated_at timestamp(6) not null,
        primary key (id)
    );

    create table document_reminders (
        id bigint generated by default as identity,
        project_id bigint not null,
        reminded_at timestamp(6) not null,
        reminded_by bigint,
        section_id bigint not null,
        message text,
        recipient varchar(100) not null,
        primary key (id)
    );

    create table document_structures (
        created_at timestamp(6),
        id bigint generated by default as identity,
        project_id bigint not null,
        root_section_id bigint,
        updated_at timestamp(6),
        name varchar(255) not null,
        primary key (id)
    );

    create table document_versions (
        is_current boolean,
        version_number integer not null,
        created_at timestamp(6),
        created_by bigint,
        id bigint generated by default as identity,
        project_id bigint not null,
        change_summary varchar(255),
        content TEXT,
        document_id varchar(255),
        file_path varchar(255),
        primary key (id)
    );

    create table expense_approval_records (
        acted_at timestamp(6) not null,
        expense_id bigint not null,
        id bigint generated by default as identity,
        result varchar(30) not null check (result in ('APPROVED','REJECTED')),
        approver varchar(100) not null,
        comment varchar(500),
        primary key (id)
    );

    create table expenses (
        amount numeric(19,2) not null,
        date date not null,
        approved_at timestamp(6),
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        project_id bigint not null,
        return_confirmed_at timestamp(6),
        return_requested_at timestamp(6),
        updated_at timestamp(6),
        status varchar(50) not null check (status in ('PENDING_APPROVAL','APPROVED','REJECTED','PAID','RETURN_REQUESTED','RETURNED')),
        approved_by varchar(100),
        created_by varchar(100) not null,
        expense_type varchar(100),
        approval_comment varchar(500),
        description varchar(500),
        return_comment varchar(500),
        category varchar(255) not null check (category in ('MATERIAL','LABOR','EQUIPMENT','TRANSPORTATION','SUBCONTRACTING','OVERHEAD','OTHER')),
        primary key (id)
    );

    create table fees (
        amount numeric(19,2) not null,
        created_at timestamp(6) not null,
        fee_date timestamp(6) not null,
        id bigint generated by default as identity,
        payment_date timestamp(6),
        project_id bigint not null,
        return_date timestamp(6),
        updated_at timestamp(6),
        status varchar(20) not null check (status in ('PENDING','PAID','RETURNED','CANCELLED')),
        fee_type varchar(30) not null check (fee_type in ('BID_BOND','SERVICE_FEE','DOCUMENT_FEE','TRAVEL_FEE','NOTARY_FEE','OTHER_FEE')),
        paid_by varchar(200),
        return_to varchar(200),
        remarks varchar(1000),
        primary key (id)
    );

    create table platform_accounts (
        return_count integer,
        borrowed_at timestamp(6),
        borrowed_by bigint,
        created_at timestamp(6) not null,
        due_at timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        status varchar(20) not null check (status in ('AVAILABLE','IN_USE','MAINTENANCE','DISABLED')),
        platform_type varchar(50) not null check (platform_type in ('GOV_PROCUREMENT','BIDDING_PLATFORM','CONSTRUCTION_PLATFORM','OTHER')),
        username varchar(100) not null unique,
        account_name varchar(200) not null,
        password varchar(255) not null,
        primary key (id)
    );

    create table project_documents (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        project_id bigint not null,
        uploader_id bigint,
        file_size varchar(50),
        file_type varchar(50),
        name varchar(255) not null,
        uploader_name varchar(100) not null,
        primary key (id)
    );

    create table project_reminders (
        created_at timestamp(6) not null,
        created_by bigint,
        id bigint generated by default as identity,
        project_id bigint not null,
        remind_at timestamp(6) not null,
        created_by_name varchar(100) not null,
        message text,
        recipient varchar(100) not null,
        title varchar(200) not null,
        primary key (id)
    );

    create table project_share_links (
        created_at timestamp(6) not null,
        created_by bigint,
        expires_at timestamp(6),
        id bigint generated by default as identity,
        project_id bigint not null,
        created_by_name varchar(100) not null,
        token varchar(255) not null unique,
        url varchar(500) not null,
        primary key (id)
    );

    create table project_team_members (
        member_id bigint,
        project_id bigint not null
    );

    create table projects (
        created_at timestamp(6) not null,
        end_date timestamp(6),
        id bigint generated by default as identity,
        manager_id bigint not null,
        start_date timestamp(6),
        tender_id bigint not null,
        updated_at timestamp(6),
        status varchar(20) not null check (status in ('INITIATED','PREPARING','REVIEWING','SEALING','BIDDING','ARCHIVED')),
        name varchar(500) not null,
        primary key (id)
    );

    create table qualifications (
        expiry_date date,
        issue_date date,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        file_url varchar(255),
        level varchar(255) not null check (level in ('FIRST','SECOND','THIRD','OTHER')),
        name varchar(255) not null,
        type varchar(255) not null check (type in ('CONSTRUCTION','DESIGN','SERVICE','OTHER')),
        primary key (id)
    );

    create table roi_analyses (
        estimated_cost numeric(19,2),
        estimated_profit numeric(19,2),
        estimated_revenue numeric(19,2),
        payback_period_months integer,
        roi_percentage numeric(10,2),
        analysis_date timestamp(6),
        created_by bigint,
        id bigint generated by default as identity,
        project_id bigint not null,
        assumptions TEXT,
        risk_factors TEXT,
        primary key (id)
    );

    create table score_analyses (
        is_ai_generated boolean,
        overall_score integer,
        analysis_date timestamp(6),
        analyst_id bigint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        project_id bigint not null,
        updated_at timestamp(6),
        risk_level varchar(20) check (risk_level in ('LOW','MEDIUM','HIGH')),
        summary TEXT,
        primary key (id)
    );

    create table tasks (
        assignee_id bigint,
        created_at timestamp(6) not null,
        due_date timestamp(6),
        id bigint generated by default as identity,
        project_id bigint not null,
        updated_at timestamp(6),
        description TEXT,
        priority varchar(255) not null check (priority in ('LOW','MEDIUM','HIGH','URGENT')),
        status varchar(255) not null check (status in ('TODO','IN_PROGRESS','COMPLETED','CANCELLED')),
        title varchar(255) not null,
        primary key (id)
    );

    create table template_tags (
        template_id bigint not null,
        tag varchar(255)
    );

    create table template_download_records (
        downloaded_at timestamp(6) not null,
        downloaded_by bigint,
        id bigint generated by default as identity,
        template_id bigint not null,
        primary key (id)
    );

    create table template_use_records (
        id bigint generated by default as identity,
        project_id bigint,
        template_id bigint not null,
        used_at timestamp(6) not null,
        used_by bigint,
        applied_options varchar(1000),
        doc_type varchar(100) not null,
        document_name varchar(255) not null,
        primary key (id)
    );

    create table template_versions (
        created_at timestamp(6) not null,
        created_by bigint,
        id bigint generated by default as identity,
        template_id bigint not null,
        description varchar(1000),
        snapshot_name varchar(255) not null,
        version varchar(50) not null,
        primary key (id)
    );

    create table templates (
        created_at timestamp(6) not null,
        created_by bigint,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        category varchar(255) not null check (category in ('TECHNICAL','COMMERCIAL','LEGAL','QUALIFICATION','CONTRACT','OTHER')),
        current_version varchar(50),
        file_size varchar(100),
        file_url varchar(255),
        name varchar(255) not null,
        description varchar(2000),
        primary key (id)
    );

    create table tenders (
        ai_score integer,
        budget numeric(19,2),
        created_at timestamp(6) not null,
        deadline timestamp(6),
        id bigint generated by default as identity,
        updated_at timestamp(6),
        risk_level varchar(20) check (risk_level in ('LOW','MEDIUM','HIGH')),
        status varchar(20) not null check (status in ('PENDING','TRACKING','BIDDED','ABANDONED')),
        source varchar(200),
        title varchar(500) not null,
        primary key (id)
    );

    create table users (
        enabled boolean not null,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        updated_at timestamp(6),
        email varchar(255) not null unique,
        full_name varchar(255) not null,
        password varchar(255) not null,
        role varchar(255) not null check (role in ('ADMIN','MANAGER','STAFF')),
        username varchar(255) not null unique,
        primary key (id)
    );

    create index idx_template_category 
       on assembly_templates (category);

    create index idx_template_created_by 
       on assembly_templates (created_by);

    create index idx_audit_user 
       on audit_logs (user_id);

    create index idx_audit_action 
       on audit_logs (action);

    create index idx_audit_timestamp 
       on audit_logs (timestamp);

    create index idx_audit_entity 
       on audit_logs (entity_type, entity_id);

    create index idx_event_date 
       on calendar_events (event_date);

    create index idx_event_type 
       on calendar_events (event_type);

    create index idx_calendar_events_project_id 
       on calendar_events (project_id);

    create index idx_urgent 
       on calendar_events (is_urgent);

    create index idx_date_range 
       on calendar_events (event_date, event_type);

    create index idx_thread_project 
       on collaboration_threads (project_id);

    create index idx_thread_status 
       on collaboration_threads (status);

    create index idx_thread_project_status 
       on collaboration_threads (project_id, status);

    create index idx_comment_thread 
       on comments (thread_id);

    create index idx_comment_user 
       on comments (user_id);

    create index idx_comment_parent 
       on comments (parent_id);

    create index idx_comment_deleted 
       on comments (is_deleted);

    create index idx_comment_thread_deleted 
       on comments (thread_id, is_deleted);

    create index idx_competition_analyses_project 
       on competition_analyses (project_id);

    create index idx_analysis_competitor 
       on competition_analyses (competitor_id);

    create index idx_competition_analyses_date 
       on competition_analyses (analysis_date);

    create index idx_analysis_project_competitor 
       on competition_analyses (project_id, competitor_id);

    create index idx_competitor_name 
       on competitors (name);

    create index idx_competitor_industry 
       on competitors (industry);

    create index idx_result_project 
       on compliance_check_results (project_id);

    create index idx_result_tender 
       on compliance_check_results (tender_id);

    create index idx_result_status 
       on compliance_check_results (overall_status);

    create index idx_result_checked_at 
       on compliance_check_results (checked_at);

    create index idx_rule_type 
       on compliance_rules (rule_type);

    create index idx_rule_enabled 
       on compliance_rules (enabled);

    create index idx_dimension_analysis 
       on dimension_scores (analysis_id);

    create index idx_dimension_name 
       on dimension_scores (dimension_name);

    create index idx_assembly_project 
       on document_assemblies (project_id);

    create index idx_assembly_template 
       on document_assemblies (template_id);

    create index idx_assembly_project_template 
       on document_assemblies (project_id, template_id);

    create index idx_document_versions_project_id 
       on document_versions (project_id);

    create index idx_document_id 
       on document_versions (document_id);

    create index idx_project_current 
       on document_versions (project_id, is_current);

    create index idx_fee_project 
       on fees (project_id);

    create index idx_fee_status 
       on fees (status);

    create index idx_fee_type 
       on fees (fee_type);

    create index idx_fee_project_status 
       on fees (project_id, status);

    create index idx_platform_username 
       on platform_accounts (username);

    create index idx_platform_status 
       on platform_accounts (status);

    create index idx_platform_type 
       on platform_accounts (platform_type);

    create index idx_platform_borrowed_by 
       on platform_accounts (borrowed_by);

    create index idx_project_status 
       on projects (status);

    create index idx_project_manager 
       on projects (manager_id);

    create index idx_project_tender 
       on projects (tender_id);

    create index idx_project_dates 
       on projects (start_date, end_date);

    create index idx_project_documents_project
       on project_documents (project_id);

    create index idx_project_reminders_project
       on project_reminders (project_id);

    create index idx_project_share_links_project
       on project_share_links (project_id);

    create index idx_roi_project 
       on roi_analyses (project_id);

    create index idx_roi_analysis_date 
       on roi_analyses (analysis_date);

    create index idx_score_analyses_project 
       on score_analyses (project_id);

    create index idx_score_analyses_date 
       on score_analyses (analysis_date);

    create index idx_analysis_risk 
       on score_analyses (risk_level);

    create index idx_tender_status 
       on tenders (status);

    create index idx_tender_source 
       on tenders (source);

    create index idx_tender_deadline 
       on tenders (deadline);

    create index idx_tender_ai_score 
       on tenders (ai_score);

    alter table if exists project_team_members 
       add constraint FKrplt19ljycvlrk9fy72yep75e 
       foreign key (project_id) 
       references projects;

    alter table if exists template_tags 
       add constraint FKb690bd7lptenw09h0u23iwila 
       foreign key (template_id) 
       references templates;

    alter table if exists template_download_records
       add constraint fk_template_download_records_template
       foreign key (template_id)
       references templates;

    alter table if exists template_use_records
       add constraint fk_template_use_records_template
       foreign key (template_id)
       references templates;

    alter table if exists template_versions
       add constraint fk_template_versions_template
       foreign key (template_id)
       references templates;

    create table bar_site_accounts (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        bar_asset_id bigint not null,
        updated_at timestamp(6),
        email varchar(200),
        owner varchar(100) not null,
        phone varchar(50) not null,
        role varchar(30) not null,
        status varchar(30) not null,
        username varchar(100) not null,
        primary key (id)
    );

    create table bar_site_sops (
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        bar_asset_id bigint not null unique,
        updated_at timestamp(6),
        estimated_time varchar(100),
        reset_url varchar(500),
        unlock_url varchar(500),
        contacts_json TEXT,
        faqs_json TEXT,
        history_json TEXT,
        required_docs_json TEXT,
        primary key (id)
    );

    create table bar_site_attachments (
        uploaded_at timestamp(6) not null,
        bar_asset_id bigint not null,
        id bigint generated by default as identity,
        content_type varchar(100),
        size varchar(50),
        uploaded_by varchar(100),
        name varchar(200) not null,
        url varchar(500),
        primary key (id)
    );

    create table bar_site_verifications (
        verified_at timestamp(6) not null,
        bar_asset_id bigint not null,
        id bigint generated by default as identity,
        status varchar(30) not null,
        message varchar(500),
        verified_by varchar(100) not null,
        primary key (id)
    );

    create index idx_bar_site_accounts_asset_id
       on bar_site_accounts (bar_asset_id);

    create index idx_bar_site_attachments_asset_id
       on bar_site_attachments (bar_asset_id);

    create index idx_bar_site_verifications_asset_id
       on bar_site_verifications (bar_asset_id);

    alter table if exists bar_site_accounts
       add constraint fk_bar_site_accounts_asset
       foreign key (bar_asset_id)
       references bar_assets;

    alter table if exists bar_site_sops
       add constraint fk_bar_site_sops_asset
       foreign key (bar_asset_id)
       references bar_assets;

    alter table if exists bar_site_attachments
       add constraint fk_bar_site_attachments_asset
       foreign key (bar_asset_id)
       references bar_assets;

    alter table if exists bar_site_verifications
       add constraint fk_bar_site_verifications_asset
       foreign key (bar_asset_id)
       references bar_assets;
