create table document_assignments (
    due_date date,
    assigned_by bigint,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    project_id bigint not null,
    section_id bigint not null unique,
    updated_at timestamp(6) not null,
    owner varchar(100) not null,
    primary key (id)
);

create table document_locks (
    locked boolean not null,
    created_at timestamp(6) not null,
    id bigint generated by default as identity,
    locked_at timestamp(6),
    locked_by bigint,
    project_id bigint not null,
    section_id bigint not null unique,
    updated_at timestamp(6) not null,
    primary key (id)
);

create table document_reminders (
    id bigint generated by default as identity,
    project_id bigint not null,
    reminded_at timestamp(6) not null,
    reminded_by bigint,
    section_id bigint not null,
    message text,
    recipient varchar(100) not null,
    primary key (id)
);

create index idx_document_assignments_project on document_assignments (project_id);
create index idx_document_locks_project on document_locks (project_id);
create index idx_document_reminders_project_section on document_reminders (project_id, section_id);
