create table if not exists project_documents (
    id bigint generated by default as identity,
    project_id bigint not null,
    uploader_id bigint,
    created_at timestamp(6) not null,
    file_size varchar(50),
    file_type varchar(50),
    name varchar(255) not null,
    uploader_name varchar(100) not null,
    primary key (id)
);

create table if not exists project_reminders (
    id bigint generated by default as identity,
    created_at timestamp(6) not null,
    created_by bigint,
    project_id bigint not null,
    remind_at timestamp(6) not null,
    message text,
    created_by_name varchar(100) not null,
    recipient varchar(100) not null,
    title varchar(200) not null,
    primary key (id)
);

create table if not exists project_share_links (
    id bigint generated by default as identity,
    created_at timestamp(6) not null,
    created_by bigint,
    expires_at timestamp(6),
    project_id bigint not null,
    created_by_name varchar(100) not null,
    token varchar(255) not null unique,
    url varchar(500) not null,
    primary key (id)
);

create index if not exists idx_project_documents_project on project_documents (project_id);
create index if not exists idx_project_reminders_project on project_reminders (project_id);
create index if not exists idx_project_share_links_project on project_share_links (project_id);
