-- Phase 1: Extend tasks.status CHECK constraint to include REVIEW
alter table tasks drop constraint if exists tasks_status_check;
alter table tasks add constraint tasks_status_check
    check (status in ('TODO','IN_PROGRESS','REVIEW','COMPLETED','CANCELLED'));

-- Phase 2: Create task_deliverables table
create table task_deliverables (
    id                  bigint generated by default as identity primary key,
    task_id             bigint not null references tasks(id) on delete cascade,
    name                varchar(255) not null,
    deliverable_type    varchar(30) not null check (deliverable_type in (
        'DOCUMENT','QUALIFICATION','TECHNICAL','QUOTATION','OTHER'
    )),
    file_size           varchar(50),
    file_type           varchar(100),
    storage_path        varchar(500),
    storage_key         varchar(255) unique,
    version             integer not null default 1,
    uploader_id         bigint,
    uploader_name       varchar(100) not null,
    created_at          timestamp(6) not null default now()
);

create index idx_task_deliverables_task_id on task_deliverables(task_id);
create index idx_task_deliverables_type on task_deliverables(deliverable_type);
