-- Create table if it doesn't exist
CREATE TABLE IF NOT EXISTS competitor_win_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competitor_id BIGINT NOT NULL,
    competitor_name VARCHAR(200) NOT NULL,
    project_id BIGINT,
    project_name VARCHAR(500),
    sku_count INTEGER,
    category VARCHAR(200),
    discount VARCHAR(100),
    payment_terms VARCHAR(200),
    won_at DATE,
    amount NUMERIC(19, 2),
    notes VARCHAR(2000),
    recorded_by BIGINT,
    recorded_name VARCHAR(100),
    created_at TIMESTAMP(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_competitor_win_competitor ON competitor_win_records (competitor_id);
CREATE INDEX IF NOT EXISTS idx_competitor_win_project ON competitor_win_records (project_id);
CREATE INDEX IF NOT EXISTS idx_competitor_win_won_at ON competitor_win_records (won_at);
