alter table templates
    add column if not exists description varchar(2000);

alter table templates
    add column if not exists current_version varchar(50);

alter table templates
    add column if not exists file_size varchar(100);

update templates
set current_version = coalesce(current_version, '1.0'),
    file_size = coalesce(file_size, '未知')
where current_version is null
   or file_size is null;

create table if not exists template_versions (
    id bigint generated by default as identity primary key,
    template_id bigint not null,
    version varchar(50) not null,
    description varchar(1000),
    snapshot_name varchar(255) not null,
    created_by bigint,
    created_at timestamp(6) not null default current_timestamp,
    constraint fk_template_versions_template
        foreign key (template_id) references templates
);

create index if not exists idx_template_versions_template_id_created_at
    on template_versions (template_id, created_at desc);

create table if not exists template_use_records (
    id bigint generated by default as identity primary key,
    template_id bigint not null,
    document_name varchar(255) not null,
    doc_type varchar(100) not null,
    project_id bigint,
    applied_options varchar(1000),
    used_by bigint,
    used_at timestamp(6) not null default current_timestamp,
    constraint fk_template_use_records_template
        foreign key (template_id) references templates
);

create index if not exists idx_template_use_records_template_id_used_at
    on template_use_records (template_id, used_at desc);

create table if not exists template_download_records (
    id bigint generated by default as identity primary key,
    template_id bigint not null,
    downloaded_by bigint,
    downloaded_at timestamp(6) not null default current_timestamp,
    constraint fk_template_download_records_template
        foreign key (template_id) references templates
);

create index if not exists idx_template_download_records_template_id_downloaded_at
    on template_download_records (template_id, downloaded_at desc);
