create table ai_analysis_jobs (
    id bigint generated by default as identity primary key,
    analysis_type varchar(50) not null,
    target_type varchar(30) not null,
    target_id bigint not null,
    status varchar(30) not null,
    requested_by bigint,
    created_at timestamp(6) not null,
    completed_at timestamp(6),
    error_message varchar(1000)
);

create table ai_analysis_results (
    id bigint generated by default as identity primary key,
    job_id bigint,
    tender_id bigint,
    project_id bigint,
    analysis_type varchar(50) not null,
    score integer not null,
    risk_level varchar(30),
    suggestion varchar(500),
    payload_json TEXT not null,
    created_at timestamp(6) not null
);

create table project_score_previews (
    id bigint generated by default as identity primary key,
    project_id bigint,
    tender_id bigint,
    project_name varchar(255),
    industry varchar(100),
    budget numeric(19,2),
    tags_json TEXT,
    win_score integer not null,
    win_level varchar(20) not null,
    payload_json TEXT not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6)
);

create index idx_ai_job_target on ai_analysis_jobs (target_type, target_id);
create index idx_ai_job_status on ai_analysis_jobs (status);
create index idx_ai_result_tender on ai_analysis_results (tender_id, created_at);
create index idx_ai_result_project on ai_analysis_results (project_id, created_at);
create index idx_ai_result_job on ai_analysis_results (job_id);
create index idx_score_preview_project on project_score_previews (project_id, created_at);
create index idx_score_preview_tender on project_score_previews (tender_id, created_at);

alter table if exists ai_analysis_results
    add constraint fk_ai_result_job
    foreign key (job_id)
    references ai_analysis_jobs;

alter table if exists ai_analysis_results
    add constraint fk_ai_result_tender
    foreign key (tender_id)
    references tenders;

alter table if exists ai_analysis_results
    add constraint fk_ai_result_project
    foreign key (project_id)
    references projects;

alter table if exists project_score_previews
    add constraint fk_score_preview_project
    foreign key (project_id)
    references projects;

alter table if exists project_score_previews
    add constraint fk_score_preview_tender
    foreign key (tender_id)
    references tenders;
