create table if not exists historical_project_snapshots (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    archive_record_id bigint not null unique,
    export_id bigint not null,
    project_name varchar(500) not null,
    customer_name varchar(255),
    product_line varchar(255),
    archive_summary text not null,
    document_snapshot_text text not null,
    recommended_tags text,
    captured_at timestamp(6) not null default current_timestamp
);

create index if not exists idx_history_snapshot_project
    on historical_project_snapshots (project_id);

create index if not exists idx_history_snapshot_archive
    on historical_project_snapshots (archive_record_id);

create index if not exists idx_history_snapshot_export
    on historical_project_snapshots (export_id);
