alter table alert_history
    add column if not exists acknowledged_at timestamp(6);

create table if not exists tender_assignment_records (
    id bigint generated by default as identity,
    tender_id bigint not null,
    assignee_id bigint not null,
    assigned_by_id bigint,
    assigned_at timestamp(6) not null,
    assignee_name varchar(255) not null,
    assigned_by_name varchar(255),
    remark text,
    primary key (id)
);

create index if not exists idx_tender_assignment_records_tender
    on tender_assignment_records (tender_id);

create index if not exists idx_tender_assignment_records_assignee
    on tender_assignment_records (assignee_id);

create index if not exists idx_tender_assignment_records_assigned_at
    on tender_assignment_records (assigned_at desc);
