create table if not exists project_quality_checks (
    id bigint generated by default as identity,
    project_id bigint not null,
    document_id bigint,
    document_name varchar(500),
    status varchar(30) not null,
    empty boolean not null default false,
    summary TEXT,
    checked_at timestamp(6) not null default current_timestamp,
    primary key (id)
);

create index if not exists idx_project_quality_checks_project_checked_at
    on project_quality_checks (project_id, checked_at desc);

create table if not exists project_quality_issues (
    id bigint generated by default as identity,
    check_id bigint not null,
    type varchar(50) not null,
    original_text TEXT,
    suggestion_text TEXT,
    location_label varchar(500),
    adopted boolean not null default false,
    ignored boolean not null default false,
    primary key (id)
);

create index if not exists idx_project_quality_issues_check_id
    on project_quality_issues (check_id, id);
