create table if not exists contract_borrow_applications (
    id bigint generated by default as identity,
    contract_no varchar(100) not null,
    contract_name varchar(255) not null,
    source_name varchar(255),
    borrower_name varchar(100) not null,
    borrower_dept varchar(100),
    customer_name varchar(255),
    purpose text,
    borrow_type varchar(100),
    expected_return_date date,
    submitted_at timestamp(6) not null,
    approver_name varchar(100),
    approved_at timestamp(6),
    rejection_reason text,
    rejected_at timestamp(6),
    return_remark text,
    returned_at timestamp(6),
    cancel_reason text,
    cancelled_at timestamp(6),
    last_comment text,
    status varchar(32) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    primary key (id)
);

create table if not exists contract_borrow_events (
    id bigint generated by default as identity,
    application_id bigint not null,
    event_type varchar(32) not null,
    status_after varchar(32) not null,
    actor_name varchar(100),
    comment text,
    created_at timestamp(6) not null,
    primary key (id)
);

create index if not exists idx_contract_borrow_status
    on contract_borrow_applications (status);

create index if not exists idx_contract_borrow_expected_return
    on contract_borrow_applications (expected_return_date);

create index if not exists idx_contract_borrow_borrower
    on contract_borrow_applications (borrower_name);

create index if not exists idx_contract_borrow_events_application
    on contract_borrow_events (application_id, created_at);
