create table if not exists project_score_drafts (
    id bigint generated by default as identity,
    project_id bigint not null,
    source_file_name varchar(255) not null,
    category varchar(50) not null,
    score_item_title varchar(255) not null,
    score_rule_text text not null,
    score_value_text varchar(100),
    task_action varchar(50) not null,
    generated_task_title varchar(255) not null,
    generated_task_description text not null,
    suggested_deliverables text not null,
    assignee_id bigint,
    assignee_name varchar(100),
    due_date timestamp(6),
    status varchar(20) not null,
    skip_reason varchar(255),
    source_page integer,
    source_table_index integer not null,
    source_row_index integer not null,
    generated_task_id bigint,
    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,
    primary key (id)
);

create index if not exists idx_project_score_drafts_project
    on project_score_drafts (project_id);

create index if not exists idx_project_score_drafts_status
    on project_score_drafts (project_id, status);
