alter table cases
    add column if not exists customer_name varchar(255);

alter table cases
    add column if not exists location_name varchar(255);

alter table cases
    add column if not exists project_period varchar(255);

alter table cases
    add column if not exists view_count bigint not null default 0;

alter table cases
    add column if not exists use_count bigint not null default 0;

create table if not exists case_tags (
    case_id bigint not null,
    tag varchar(255)
);

create table if not exists case_highlights (
    case_id bigint not null,
    highlight varchar(1000)
);

create table if not exists case_technologies (
    case_id bigint not null,
    technology varchar(255)
);

create table if not exists case_share_records (
    id bigint generated by default as identity primary key,
    case_id bigint not null,
    token varchar(255) not null unique,
    url varchar(500) not null,
    created_by bigint,
    created_by_name varchar(100) not null,
    expires_at timestamp(6),
    created_at timestamp(6) not null default current_timestamp,
    constraint fk_case_share_records_case
        foreign key (case_id) references cases
);

create index if not exists idx_case_share_records_case_id_created_at
    on case_share_records (case_id, created_at desc);

create table if not exists case_reference_records (
    id bigint generated by default as identity primary key,
    case_id bigint not null,
    referenced_by bigint,
    referenced_by_name varchar(100) not null,
    reference_target varchar(255) not null,
    reference_context varchar(1000),
    referenced_at timestamp(6) not null default current_timestamp,
    constraint fk_case_reference_records_case
        foreign key (case_id) references cases
);

create index if not exists idx_case_reference_records_case_id_referenced_at
    on case_reference_records (case_id, referenced_at desc);
