create table if not exists document_exports (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    structure_id bigint not null,
    project_name varchar(255) not null,
    format varchar(30) not null,
    file_name varchar(255) not null,
    content_type varchar(255) not null,
    file_size bigint not null,
    exported_by bigint,
    exported_by_name varchar(255) not null,
    exported_at timestamp(6) not null
);

create index if not exists idx_document_export_project
    on document_exports (project_id);

create index if not exists idx_document_export_structure
    on document_exports (structure_id);

create table if not exists document_export_files (
    id bigint generated by default as identity primary key,
    export_id bigint not null unique,
    content text not null
);

create index if not exists idx_document_export_file_export
    on document_export_files (export_id);

create table if not exists document_archive_records (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    structure_id bigint not null,
    archived_by bigint,
    archived_by_name varchar(255) not null,
    archive_reason varchar(255) not null,
    export_id bigint,
    archived_at timestamp(6) not null
);

create index if not exists idx_document_archive_project
    on document_archive_records (project_id);

create index if not exists idx_document_archive_structure
    on document_archive_records (structure_id);
