CREATE TABLE IF NOT EXISTS organization_departments (
  department_code VARCHAR(100) PRIMARY KEY,
  department_name VARCHAR(100) NOT NULL,
  parent_department_code VARCHAR(100),
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS organization_event_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key VARCHAR(128) NOT NULL UNIQUE,
  event_topic VARCHAR(100) NOT NULL,
  source_app VARCHAR(100) NOT NULL,
  trace_id VARCHAR(128) NOT NULL,
  payload_hash VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  message VARCHAR(500),
  received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processed_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_organization_event_logs_status
  ON organization_event_logs(status);

CREATE INDEX IF NOT EXISTS idx_organization_event_logs_received_at
  ON organization_event_logs(received_at);
