CREATE TABLE IF NOT EXISTS workflow_form_template_drafts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_code VARCHAR(80) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  business_type VARCHAR(64) NOT NULL,
  draft_schema_json TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS workflow_form_template_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  template_code VARCHAR(80) NOT NULL,
  name VARCHAR(120) NOT NULL,
  business_type VARCHAR(64) NOT NULL,
  version INTEGER NOT NULL,
  schema_json TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  published_by VARCHAR(120),
  published_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_workflow_form_template_versions UNIQUE(template_code, version)
);

CREATE INDEX IF NOT EXISTS idx_workflow_form_template_versions_code ON workflow_form_template_versions(template_code, version);

INSERT INTO workflow_form_template_drafts(template_code, name, business_type, draft_schema_json, enabled, status)
SELECT template_code, name, business_type, schema_json, enabled, 'PUBLISHED'
FROM workflow_form_templates
WHERE NOT EXISTS (
  SELECT 1 FROM workflow_form_template_drafts d WHERE d.template_code = workflow_form_templates.template_code
);

INSERT INTO workflow_form_template_versions(template_code, name, business_type, version, schema_json, enabled, published_by)
SELECT template_code, name, business_type, version, schema_json, enabled, 'migration'
FROM workflow_form_templates
WHERE NOT EXISTS (
  SELECT 1 FROM workflow_form_template_versions v
  WHERE v.template_code = workflow_form_templates.template_code AND v.version = workflow_form_templates.version
);

ALTER TABLE workflow_form_instances ADD COLUMN IF NOT EXISTS template_version INTEGER;
ALTER TABLE workflow_form_instances ADD COLUMN IF NOT EXISTS schema_snapshot_json TEXT;
ALTER TABLE workflow_form_instances ADD COLUMN IF NOT EXISTS oa_binding_snapshot_json TEXT;
ALTER TABLE workflow_form_instances ADD COLUMN IF NOT EXISTS oa_payload_json TEXT;
