CREATE TABLE IF NOT EXISTS sys_crm_customer_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL,
    permission_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_crm_perm_customer
    ON sys_crm_customer_permission(customer_id);

CREATE INDEX IF NOT EXISTS idx_crm_perm_user
    ON sys_crm_customer_permission(user_id);

CREATE TABLE IF NOT EXISTS sys_project_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    member_role VARCHAR(50),
    permission_level VARCHAR(50) NOT NULL,
    is_inherited BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_project_user UNIQUE (project_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_project_member_project
    ON sys_project_member(project_id);

CREATE INDEX IF NOT EXISTS idx_project_member_user
    ON sys_project_member(user_id);
