<template>
  <el-main class="main-content">
    <ProjectBasicInfoCard :project="ctx.project" />
    <ProjectApprovalStatusCard :approval-history="ctx.approvalHistory" :project-status="ctx.project?.status" :can-approve-current="ctx.canApproveCurrent" @quick-approve="ctx.handleQuickApprove" @quick-reject="ctx.handleQuickReject" />
    <ProjectExpenseSummaryCard :expenses="ctx.projectExpenses" :summary="ctx.expenseSummary" :loading="ctx.expenseLoading" :error="ctx.expenseError" @manage="ctx.goToExpensePage" />
    <ProjectTaskBoardCard :tasks="ctx.project?.tasks || []" :project-id="ctx.project?.id" :can-manage-project-tasks="ctx.canManageProjectTasks" :is-demo-mode="ctx.isDemoMode" @add-task="ctx.handleAddTask" @reset-tasks="ctx.handleResetTasks" @task-click="ctx.handleTaskClick" @generate-tasks="ctx.handleGenerateTasks" @add-deliverable="ctx.handleAddDeliverable" @remove-deliverable="ctx.handleRemoveDeliverable" @submit-to-document="ctx.handleSubmitToDocument" />
    <el-card class="process-card"><template #header><div class="card-title"><el-icon><DocumentChecked /></el-icon><span>标书编制流程</span><el-button v-if="!ctx.bidProcess.initiated" type="primary" size="small" @click="ctx.handleInitiateProcess">发起流程</el-button></div></template><div v-if="!ctx.bidProcess.initiated" class="process-empty"><el-empty description="暂未发起标书编制流程"><el-button type="primary" @click="ctx.handleInitiateProcess">立即发起</el-button></el-empty></div><div v-else class="process-content"><el-steps :active="ctx.bidProcess.currentStep" align-center finish-status="success"><el-step title="初稿编制" :description="ctx.getStepStatusText('draft')" /><el-step title="内部评审" :description="ctx.getStepStatusText('review')" /><el-step title="用印申请" :description="ctx.getStepStatusText('seal')" /><el-step title="封装提交" :description="ctx.getStepStatusText('submit')" /></el-steps><div class="process-actions"><el-button :type="ctx.bidProcess.steps.draft.completed ? 'success' : 'primary'" :disabled="!ctx.canOperateStep('draft')" @click="ctx.handleDraftSubmit">{{ ctx.bidProcess.steps.draft.completed ? '初稿已提交' : '提交初稿' }}</el-button><el-button :type="ctx.bidProcess.steps.review.completed ? 'success' : 'warning'" :disabled="!ctx.canOperateStep('review')" @click="ctx.handleReview">{{ ctx.bidProcess.steps.review.completed ? '评审已完成' : '发起评审' }}</el-button><el-button :type="ctx.bidProcess.steps.seal.completed ? 'success' : 'primary'" :disabled="!ctx.canOperateStep('seal')" @click="ctx.handleSealApply">{{ ctx.bidProcess.steps.seal.completed ? '用印已完成' : '用印申请' }}</el-button><el-button :type="ctx.bidProcess.steps.submit.completed ? 'success' : 'primary'" :disabled="!ctx.canOperateStep('submit')" @click="ctx.handleSubmit">{{ ctx.bidProcess.steps.submit.completed ? '已封装提交' : '封装提交' }}</el-button></div></div></el-card>
    <el-card class="document-card"><template #header><div class="card-title"><el-icon><Folder /></el-icon><span>项目文档</span><el-button v-if="ctx.canManageProjectDocuments" link type="success" :icon="DocumentChecked" @click="ctx.handleArchiveDocuments">归档资料</el-button><el-upload v-if="ctx.canManageProjectDocuments" :show-file-list="false" :before-upload="ctx.handleUpload" accept=".doc,.docx,.pdf,.xls,.xlsx"><el-button link type="primary" :icon="Upload">上传文档</el-button></el-upload></div></template><el-table :data="ctx.project?.documents || []" style="width: 100%"><el-table-column prop="name" label="文档名称" min-width="200"><template #default="{ row }"><div class="file-name"><el-icon><Document /></el-icon><span>{{ row.name }}</span></div></template></el-table-column><el-table-column prop="uploader" label="上传者" width="120" /><el-table-column prop="time" label="上传时间" width="160" /><el-table-column prop="size" label="文件大小" width="100" /><el-table-column label="操作" width="120"><template #default="{ row }"><el-button link type="primary" @click="ctx.handleDownload(row)">下载</el-button><el-button link type="danger" @click="ctx.handleDeleteDoc(row)">删除</el-button></template></el-table-column></el-table><el-empty v-if="!ctx.project?.documents?.length" description="暂无文档" /></el-card>
  </el-main>
</template>

<script setup>
import { Document, DocumentChecked, Folder, Upload } from '@element-plus/icons-vue'
import { useProjectDetailContext } from '@/composables/projectDetail/context.js'
import ProjectApprovalStatusCard from '@/components/project/ProjectApprovalStatusCard.vue'
import ProjectBasicInfoCard from '@/components/project/ProjectBasicInfoCard.vue'
import ProjectExpenseSummaryCard from '@/components/project/ProjectExpenseSummaryCard.vue'
import ProjectTaskBoardCard from '@/components/project/ProjectTaskBoardCard.vue'

const ctx = useProjectDetailContext()
</script>
