-- Input: migration/B2__full_schema_baseline.sql
-- Output: rollback script for postgres environments; review data-loss comments before production use.
-- Pos: Flyway historical down migration coverage for 西域数智化投标管理平台.
-- 维护声明: source migration changes must update this rollback script in the same branch.

DROP INDEX IF EXISTS idx_project_score_drafts_status;
DROP INDEX IF EXISTS idx_project_score_drafts_project;
DROP TABLE IF EXISTS project_score_drafts;
ALTER TABLE bar_site_verifications DROP CONSTRAINT IF EXISTS fk_bar_site_verifications_asset;
ALTER TABLE bar_site_attachments DROP CONSTRAINT IF EXISTS fk_bar_site_attachments_asset;
ALTER TABLE bar_site_sops DROP CONSTRAINT IF EXISTS fk_bar_site_sops_asset;
ALTER TABLE bar_site_accounts DROP CONSTRAINT IF EXISTS fk_bar_site_accounts_asset;
DROP INDEX IF EXISTS idx_bar_site_verifications_asset_id;
DROP INDEX IF EXISTS idx_bar_site_attachments_asset_id;
DROP INDEX IF EXISTS idx_bar_site_accounts_asset_id;
DROP TABLE IF EXISTS bar_site_verifications;
DROP TABLE IF EXISTS bar_site_attachments;
DROP TABLE IF EXISTS bar_site_sops;
DROP TABLE IF EXISTS bar_site_accounts;
ALTER TABLE template_versions DROP CONSTRAINT IF EXISTS fk_template_versions_template;
ALTER TABLE template_use_records DROP CONSTRAINT IF EXISTS fk_template_use_records_template;
ALTER TABLE template_download_records DROP CONSTRAINT IF EXISTS fk_template_download_records_template;
ALTER TABLE template_tags DROP CONSTRAINT IF EXISTS FKb690bd7lptenw09h0u23iwila;
ALTER TABLE expense_payment_records DROP CONSTRAINT IF EXISTS FK_expense_payment_records_expense;
ALTER TABLE project_team_members DROP CONSTRAINT IF EXISTS FKrplt19ljycvlrk9fy72yep75e;
DROP INDEX IF EXISTS idx_tender_ai_score;
DROP INDEX IF EXISTS idx_tender_deadline;
DROP INDEX IF EXISTS idx_tender_source;
DROP INDEX IF EXISTS idx_tender_status;
DROP INDEX IF EXISTS idx_analysis_risk;
DROP INDEX IF EXISTS idx_score_analyses_date;
DROP INDEX IF EXISTS idx_score_analyses_project;
DROP INDEX IF EXISTS idx_roi_analysis_date;
DROP INDEX IF EXISTS idx_roi_project;
DROP INDEX IF EXISTS idx_project_share_links_project;
DROP INDEX IF EXISTS idx_project_reminders_project;
DROP INDEX IF EXISTS idx_project_documents_project;
DROP INDEX IF EXISTS idx_project_dates;
DROP INDEX IF EXISTS idx_project_tender;
DROP INDEX IF EXISTS idx_project_manager;
DROP INDEX IF EXISTS idx_project_status;
DROP INDEX IF EXISTS idx_platform_borrowed_by;
DROP INDEX IF EXISTS idx_platform_type;
DROP INDEX IF EXISTS idx_platform_status;
DROP INDEX IF EXISTS idx_platform_username;
DROP INDEX IF EXISTS idx_expense_payment_records_paid_at;
DROP INDEX IF EXISTS idx_expense_payment_records_expense_id;
DROP INDEX IF EXISTS idx_fee_project_status;
DROP INDEX IF EXISTS idx_fee_type;
DROP INDEX IF EXISTS idx_fee_status;
DROP INDEX IF EXISTS idx_fee_project;
DROP INDEX IF EXISTS idx_project_current;
DROP INDEX IF EXISTS idx_document_id;
DROP INDEX IF EXISTS idx_document_versions_project_id;
DROP INDEX IF EXISTS idx_assembly_project_template;
DROP INDEX IF EXISTS idx_assembly_template;
DROP INDEX IF EXISTS idx_assembly_project;
DROP INDEX IF EXISTS idx_dimension_name;
DROP INDEX IF EXISTS idx_dimension_analysis;
DROP INDEX IF EXISTS idx_rule_enabled;
DROP INDEX IF EXISTS idx_rule_type;
DROP INDEX IF EXISTS idx_result_checked_at;
DROP INDEX IF EXISTS idx_result_status;
DROP INDEX IF EXISTS idx_result_tender;
DROP INDEX IF EXISTS idx_result_project;
DROP INDEX IF EXISTS idx_competitor_industry;
DROP INDEX IF EXISTS idx_competitor_name;
DROP INDEX IF EXISTS idx_analysis_project_competitor;
DROP INDEX IF EXISTS idx_competition_analyses_date;
DROP INDEX IF EXISTS idx_analysis_competitor;
DROP INDEX IF EXISTS idx_competition_analyses_project;
DROP INDEX IF EXISTS idx_comment_thread_deleted;
DROP INDEX IF EXISTS idx_comment_deleted;
DROP INDEX IF EXISTS idx_comment_parent;
DROP INDEX IF EXISTS idx_comment_user;
DROP INDEX IF EXISTS idx_comment_thread;
DROP INDEX IF EXISTS idx_thread_project_status;
DROP INDEX IF EXISTS idx_thread_status;
DROP INDEX IF EXISTS idx_thread_project;
DROP INDEX IF EXISTS idx_date_range;
DROP INDEX IF EXISTS idx_urgent;
DROP INDEX IF EXISTS idx_calendar_events_project_id;
DROP INDEX IF EXISTS idx_event_type;
DROP INDEX IF EXISTS idx_event_date;
DROP INDEX IF EXISTS idx_audit_entity;
DROP INDEX IF EXISTS idx_audit_timestamp;
DROP INDEX IF EXISTS idx_audit_action;
DROP INDEX IF EXISTS idx_audit_user;
DROP INDEX IF EXISTS idx_template_created_by;
DROP INDEX IF EXISTS idx_template_category;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS tenders;
DROP TABLE IF EXISTS templates;
DROP TABLE IF EXISTS template_versions;
DROP TABLE IF EXISTS template_use_records;
DROP TABLE IF EXISTS template_download_records;
DROP TABLE IF EXISTS template_tags;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS score_analyses;
DROP TABLE IF EXISTS roi_analyses;
DROP TABLE IF EXISTS qualifications;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS project_team_members;
DROP TABLE IF EXISTS project_share_links;
DROP TABLE IF EXISTS project_reminders;
DROP TABLE IF EXISTS project_documents;
DROP TABLE IF EXISTS platform_accounts;
DROP TABLE IF EXISTS fees;
DROP TABLE IF EXISTS expense_payment_records;
DROP TABLE IF EXISTS expenses;
DROP TABLE IF EXISTS expense_approval_records;
DROP TABLE IF EXISTS document_versions;
DROP INDEX IF EXISTS idx_document_export_structure;
DROP INDEX IF EXISTS idx_document_export_project;
DROP INDEX IF EXISTS idx_document_export_file_export;
DROP INDEX IF EXISTS idx_document_archive_structure;
DROP INDEX IF EXISTS idx_document_archive_project;
DROP TABLE IF EXISTS document_structures;
DROP TABLE IF EXISTS document_reminders;
DROP TABLE IF EXISTS document_locks;
DROP TABLE IF EXISTS document_assignments;
DROP TABLE IF EXISTS document_sections;
DROP TABLE IF EXISTS document_exports;
DROP TABLE IF EXISTS document_export_files;
DROP TABLE IF EXISTS document_archive_records;
DROP TABLE IF EXISTS document_assemblies;
DROP TABLE IF EXISTS dimension_scores;
DROP TABLE IF EXISTS compliance_rules;
DROP TABLE IF EXISTS compliance_check_results;
DROP TABLE IF EXISTS competitors;
DROP TABLE IF EXISTS competition_analyses;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS collaboration_threads;
DROP TABLE IF EXISTS case_technologies;
DROP TABLE IF EXISTS case_tags;
DROP TABLE IF EXISTS case_share_records;
DROP TABLE IF EXISTS case_reference_records;
DROP TABLE IF EXISTS case_highlights;
DROP TABLE IF EXISTS cases;
DROP TABLE IF EXISTS calendar_events;
DROP TABLE IF EXISTS bar_certificates;
DROP TABLE IF EXISTS bar_certificate_borrow_records;
DROP TABLE IF EXISTS bar_assets;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS assembly_templates;
DROP TABLE IF EXISTS alert_rules;
DROP TABLE IF EXISTS alert_history;
DROP TABLE IF EXISTS accounts;
